version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout

      - run:
          name: install
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 setup.py sdist
            pip3 install $(ls dist/*.tar.gz)[testing]

      - run:
          name: flake8 check
          command: |
            . venv/bin/activate
            flake8 .

      - run:
          name: mypy check
          command: |
            . venv/bin/activate
            mypy --ignore-missing-imports .

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest tests
