version: 2

workflows:
  version: 2
  build:
    jobs:
      - build
      - build-python2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout

      - run: &install
          name: install
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            python setup.py sdist
            pip install $(ls dist/*.tar.gz)[testing]

      - run: &flake8
          name: flake8
          command: |
            . venv/bin/activate
            flake8 .

      - run: &mypy
          name: mypy
          command: |
            . venv/bin/activate
            mypy --ignore-missing-imports .
            mypy --py2 --ignore-missing-imports .

      - run: &tests
          name: tests
          command: |
            . venv/bin/activate
            pytest tests

  build-python2:
    docker:
      - image: circleci/python:2.7
    steps:
      [checkout, run: *install, run: *tests]
