version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout

      - run:
          name: install
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install pytest
            python3 setup.py sdist
            pip3 install dist/*.tar.gz

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest tests
