---
name: "\U00002753Questions"
about: Don't use GitHub Issues to ask support questions.
title: Don't use GitHub Issues to ask support questions.
labels: ''
assignees: ''

---

# PLEASE USE GITHUB DISCUSSIONS

Don't use GitHub Issues to ask support questions. Use the [GitHub Discussions](https://github.com/optuna/optuna/discussions/categories/q-a) for that.
