name: Checks (Integration)

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 23 * * SUN-THU'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get -y install openmpi-bin libopenmpi-dev libopenblas-dev

    - name: Install
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[checking]
        pip install --progress-bar off -U .[optional]
        pip install --progress-bar off -U .[integration] --extra-index-url https://download.pytorch.org/whl/cpu
        pip install --progress-bar off -U .[benchmark]

    - name: black
      run: black . --check --diff
    - name: flake8
      run: flake8 .
    - name: isort
      run: isort . --check --diff
    - name: mypy
      run: mypy .
    - name: blackdoc
      run: blackdoc . --check --diff
