# Label pull requests using https://github.com/actions/labeler.
# Note that once added to a pull request, a label will not removed, even when changes are reverted.

name: labeler

on:
- pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
