name: Publish distributions to TestPyPI and PyPI

# TestPyPI upload is scheduled in each weekday.
# PyPI upload is only activated if the release is published.
on:
  schedule:
    - cron: '0 15 * * *'
  release:
    types:
      - published

jobs:
  build-n-publish:
    name: Build and publish Python distributions to TestPyPI and PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install twine
      run: >-
        python -m pip install -U twine wheel

    - name: Create a branch and change the version file for TestPyPI upload
      if: (github.repository == 'optuna/optuna') && (github.event_name == 'schedule')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email gohome.x105.gn@gmail.com
        git config --local user.name HideakiImamura
        OPTUNA_VERSION=$( cat optuna/version.py | cut -d "\"" -f 2 )
        DATE=`date +"%Y%m%d"`
        git checkout -b ${OPTUNA_VERSION}.dev${DATE}
        echo __version__\ =\ \"${OPTUNA_VERSION}.dev${DATE}\" > optuna/version.py
        git add optuna/version.py
        git commit -m "Prepare TestPyPI upload. The version is ${OPTUNA_VERSION}.dev${DATE}"

    - name: Build a tar ball
      run: |
        python setup.py sdist
        python setup.py bdist_wheel

    - name: Verify the distributions
      run: twine check dist/*

    - name: Publish distribution to TestPyPI
      # The following upload action cannot be executed in the forked repository.
      if: (github.repository == 'optuna/optuna') && (github.event_name == 'schedule')
      uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution to PyPI
      # The following upload action cannot be executed in the forked repository.
      if: (github.repository == 'optuna/optuna') && (github.event_name == 'release')
      uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
