name: Sphinx

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  documentation:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # note (crcrpar): We've not updated tutorial frequently enough so far thus
    # it'd be okay to discard cache by any small changes including typo fix under tutorial directory.
    - name: Sphinx Gallery Cache
      uses: actions/cache@v2
      env:
        cache-name: sphx-glry-documentation
      with:
        path: |
          tutorial/MNIST
          docs/source/tutorial
        key: py3.8-${{ env.cache-name }}-${{ hashFiles('tutorial/**/*') }}

    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[document] -f https://download.pytorch.org/whl/torch_stable.html

    - name: Build Document
      run: |
        cd docs
        make html
        cd ../

    - uses: actions/upload-artifact@v2
      with:
        name: built-html
        path: |
            docs/build/html

  doctest:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Sphinx Gallery Cache
      uses: actions/cache@v2
      env:
        cache-name: sphx-glry-doctest
      with:
        path: |
          tutorial/MNIST
          docs/source/tutorial
        key: py3.8-${{ env.cache-name }}-${{ hashFiles('tutorial/**/*') }}

    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[document,doctest] -f https://download.pytorch.org/whl/torch_stable.html

    - name: Run Doctest
      run: |
        cd docs
        make doctest

  # note (crcrpar): Sphinx Gallery internally uses Pickle.
  # We found that the default protocol version of Python 3.8's pickle is incompatible with
  # that of Python3.6/3.7's pickle.
  # So, to make the artifact of executed tutorial backward-compatible as possible,
  # we employ Python3.7 and build tutorial artifacts only on master push.
  tutorial-artifacts:

    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    # note (crcrpar): We've not updated tutorial frequently enough so far thus
    # it'd be okay to discard cache by any small changes including typo fix under tutorial directory.
    - name: Sphinx Gallery Cache
      uses: actions/cache@v2
      env:
        cache-name: sphx-glry-documentation
      with:
        path: |
          tutorial/MNIST
          docs/source/tutorial
        key: py3.7-${{ env.cache-name }}-${{ hashFiles('tutorial/**/*') }}

    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install --progress-bar off -U .[document] -f https://download.pytorch.org/whl/torch_stable.html

    - name: Build Document
      run: |
        cd docs
        make html
        cd ../

    - uses: actions/upload-artifact@v2
      with:
        name: tutorial
        path: |
            docs/source/tutorial
