name: Sphinx

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  documentation:

    runs-on: ubuntu-latest

    container: readthedocs/build:latest

    steps:

    - name: Update Git
      run: |
        add-apt-repository ppa:git-core/ppa -y
        apt-get update
        apt-get install -y git
      shell: bash {0}

    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        python -m venv venv || virtualenv venv --python=python3.8
        . venv/bin/activate
        pip install -U pip
        pip install --progress-bar off -U .[document]

    - name: Build Document
      run: |
        . venv/bin/activate
        cd docs
        make html
        cd ../

    - uses: actions/upload-artifact@v2
      with:
        name: built-document
        path: docs/build

  doctest:

    runs-on: ubuntu-latest

    container: readthedocs/build:latest

    steps:

    - name: Update Git
      run: |
        add-apt-repository ppa:git-core/ppa -y
        apt-get update
        apt-get install -y git
      shell: bash {0}

    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        python -m venv venv || virtualenv venv --python=python3.8
        . venv/bin/activate
        pip install -U pip
        pip install --progress-bar off -U .[document,doctest]

    # TODO (crcrpar): Prevent sphinx-gallery build
    - name: Run Doctest
      run: |
        cd docs
        make doctest
